### ISSUE TITLE
need to change the social/around the web bit 

### ISSUE THREAD

**Issue by cameronmclean** [UoA-eResearch/HackyHour#2]
I changed the _config.yml - but do we need to recompile with jekyll for that to have an effect?
Can we just remove/replace the div from the footer.html and hard code a twitter link/icon?

**Comment by cameronmclean** [comment]
Wait - maybe it's fixed - just a lag between git push and gh-pages picking up the changes...?

**Comment by rhosking** [comment]
Nah, it will recompile itself, seems like you managed to get all it working though.


On 5/03/2015, at 8:08 pm, Cameron McLean <notifications@github.com<mailto:notifications@github.com>> wrote:


I changed the _config.yml - but do we need to recompile with jekyll for that to have an effect?
Can we just remove the

from the footer.html and hard code a twitter link/icon?

**Comment by rhosking** [comment]
Yeah, it seems to be all good! I just updated the header to state the time and location, could spend longer playing around with the styling, but I thought it was important to make that information clear, and quick to find
